spring:

  redis:
    database: 0
    host: 127.0.0.1
    password: myredis
    port: 6379
    timeout: 10000

# 数据源配置
app:
  datasource:
    mysql:
      marketing-activity:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/my_marketing_activity?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: 1234
        maximum-pool-size: 10
        minimum-idle: 1
      wangxiao:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/WangXiao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: 1234
        maximum-pool-size: 10
        minimum-idle: 1
      product:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/zhongye_product?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: 1234
        maximum-pool-size: 80
        minimum-idle: 1